/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Tablas.Encargado;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Vetto
 */
public class Interface extends javax.swing.JFrame {

    public Connection co;
    ConexionSQLbase c=new ConexionSQLbase();
    public Statement stm;
    PreparedStatement psInsertar;
    /**
     * Creates new form Interface
     */
    public Interface() {
        co=c.ConexionSQL();
        initComponents();
        this.setLocationRelativeTo(null); // Coloca la ventana en la posicion central de el escritorio
        jLabelNewUserWallpaper.setVisible(false); // Oculta el Wallpaper de New User al inicial la aplicacion
        jLabelBack.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        jTextFieldNewUserName.setVisible(false);
        jTextFieldNewUserCharge.setVisible(false);
        jPasswordNewUser1.setVisible(false);
        jPasswordNewUser2.setVisible(false);
        jLabel9.setVisible(false);
        jLabel10.setVisible(false);
        jTextFieldUserNewUser.setVisible(false);
        jPasswordUserNewUser.setVisible(false);
        jButton3.setVisible(false);
    }

    public Image getIconImage(){ // Coloca como icono de la aplicacion la imagen definida en el package
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/Icon.png"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabelUserIcon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPassword = new javax.swing.JPasswordField();
        jTextFieldUser = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabelNewUser = new javax.swing.JLabel();
        jLabelBack = new javax.swing.JLabel();
        jTextFieldNewUserName = new javax.swing.JTextField();
        jTextFieldNewUserCharge = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPasswordNewUser1 = new javax.swing.JPasswordField();
        jPasswordNewUser2 = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldUserNewUser = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPasswordUserNewUser = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        jLabelNewUserWallpaper = new javax.swing.JLabel();
        jLabelLoginWallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(102, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, -1, -1));

        jLabelUserIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/User.png"))); // NOI18N
        getContentPane().add(jLabelUserIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Contraseña:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 410, -1, -1));

        jPassword.setBackground(new java.awt.Color(0, 0, 0));
        jPassword.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPassword.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 410, 190, -1));

        jTextFieldUser.setBackground(new java.awt.Color(0, 0, 0));
        jTextFieldUser.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jTextFieldUser.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextFieldUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 350, 190, -1));

        jButton2.setBackground(new java.awt.Color(51, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Iniciar sesión");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 470, 190, -1));

        jLabelNewUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelNewUser.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNewUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/NewUser.png"))); // NOI18N
        jLabelNewUser.setText("Nuevo Usuario");
        jLabelNewUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelNewUserMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelNewUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabelBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelBack.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BackWhite.png"))); // NOI18N
        jLabelBack.setText(" Regresar");
        jLabelBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBackMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jTextFieldNewUserName.setBackground(new java.awt.Color(0, 0, 0));
        jTextFieldNewUserName.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jTextFieldNewUserName.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextFieldNewUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 190, 30));

        jTextFieldNewUserCharge.setBackground(new java.awt.Color(0, 0, 0));
        jTextFieldNewUserCharge.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jTextFieldNewUserCharge.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextFieldNewUserCharge, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 190, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Contraseña:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Contraseña:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jLabel6.setText("Nuevo usuario");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, -1, 20));

        jPasswordNewUser1.setBackground(new java.awt.Color(0, 0, 0));
        jPasswordNewUser1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPasswordNewUser1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPasswordNewUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 190, -1));

        jPasswordNewUser2.setBackground(new java.awt.Color(0, 0, 0));
        jPasswordNewUser2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPasswordNewUser2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPasswordNewUser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 190, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Usuario que autoriza");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, -1, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Cargo:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nombre:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, -1, 20));

        jTextFieldUserNewUser.setBackground(new java.awt.Color(0, 0, 0));
        jTextFieldUserNewUser.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jTextFieldUserNewUser.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextFieldUserNewUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 190, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Contraseña:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, -1, 20));

        jPasswordUserNewUser.setBackground(new java.awt.Color(0, 0, 0));
        jPasswordUserNewUser.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPasswordUserNewUser.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPasswordUserNewUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 190, -1));

        jButton3.setBackground(new java.awt.Color(51, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Crear usuario");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 530, 190, -1));

        jLabelNewUserWallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EnterUser.jpg"))); // NOI18N
        getContentPane().add(jLabelNewUserWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 960, -1));

        jLabelLoginWallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Main.jpg"))); // NOI18N
        getContentPane().add(jLabelLoginWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0); //Sale de la aplicacion
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabelNewUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNewUserMouseClicked
        // Oculta todos los elementos de inicio de sesion  y muestra todos los elementos para el registro de un nuevo usuario
        jLabelNewUserWallpaper.setVisible(true);
        jLabelBack.setVisible(true);
        jLabelLoginWallpaper.setVisible(false);
        jLabelNewUser.setVisible(false);
        jLabelUserIcon.setVisible(false);
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        jTextFieldUser.setVisible(false);
        jPassword.setVisible(false);
        jButton2.setVisible(false);
        jLabel3.setVisible(true);
        jLabel4.setVisible(true);
        jLabel5.setVisible(true);
        jLabel6.setVisible(true);
        jLabel7.setVisible(true);
        jLabel8.setVisible(true);
        jTextFieldNewUserName.setVisible(true);
        jTextFieldNewUserCharge.setVisible(true);
        jPasswordNewUser1.setVisible(true);
        jPasswordNewUser2.setVisible(true);
        jLabel9.setVisible(true);
        jLabel10.setVisible(true);
        jTextFieldUserNewUser.setVisible(true);
        jPasswordUserNewUser.setVisible(true);
        jButton3.setVisible(true);
    }//GEN-LAST:event_jLabelNewUserMouseClicked

    private void jLabelBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBackMouseClicked
        // Muestra todos los elementos de inicio de sesion  y oculta todos los elementos para el registro de un nuevo usuario
        jLabelLoginWallpaper.setVisible(true);
        jLabelNewUser.setVisible(true);
        jLabelUserIcon.setVisible(true);
        jLabel1.setVisible(true);
        jLabel2.setVisible(true);
        jTextFieldUser.setVisible(true);
        jPassword.setVisible(true);
        jButton2.setVisible(true);
        jLabelNewUserWallpaper.setVisible(false);
        jLabelBack.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        jTextFieldNewUserName.setVisible(false);
        jTextFieldNewUserCharge.setVisible(false);
        jPasswordNewUser1.setVisible(false);
        jPasswordNewUser2.setVisible(false);
        jLabel9.setVisible(false);
        jLabel10.setVisible(false);
        jTextFieldUserNewUser.setVisible(false);
        jPasswordUserNewUser.setVisible(false);
        jButton3.setVisible(false);
    }//GEN-LAST:event_jLabelBackMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        char [] pas = new char[45];
        String password=" ";
        String nombre=jTextFieldUser.getText();
        pas=jPassword.getPassword();
        password=String.copyValueOf(pas);
        System.out.print(password);
        Encargado encargado=new Encargado();
        encargado= encargado.VerificarExistenciaDeEncargado(co, nombre);
        if( encargado!=null&&encargado.getPassword().equalsIgnoreCase(password)==true){
            MainFrame ventana = new MainFrame();
            ventana.setVisible(true);
            this.setVisible(false);
        }
        else{
            JOptionPane.showMessageDialog( null, "El usuario no existe!! D:"+"\n"+"Pero tranquilo :)" + "\n"+"Puedes crear un usuario" );
            Interface interfaz = new Interface();
            this.setVisible(false);
            interfaz.setVisible(true);
        }
       /*MainFrame MainWindow = new MainFrame();
        MainWindow.setVisible(true);
        this.setVisible(false);*/
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //Botón que inicia sesión:
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        //ingresar nuevo usuario
         String nombre=jTextFieldUserNewUser.getText();
        String password=String.copyValueOf(jPasswordUserNewUser.getPassword()) ;
        Encargado encargado=new Encargado();
       encargado=encargado.VerificarExistenciaDeEncargado(co, nombre);
       if( encargado!=null&&encargado.getPassword().equals(password)==true){
            if(String.valueOf(jPasswordNewUser1.getPassword()).equals(String.valueOf(jPasswordNewUser2.getPassword()))==true){
                Encargado enca=new Encargado();
                enca.InsertarEncargado(co, jTextFieldNewUserName.getText(), jTextFieldNewUserCharge.getText(), String.valueOf(jPasswordNewUser1.getPassword()));
                JOptionPane.showMessageDialog(null, "Hola nuevo usuario");
                Interface interfaz=new Interface();
                interfaz.setVisible(true);
                this.setVisible(false);
            }
            else{
                JOptionPane.showMessageDialog( null, "La confirmación de contraseña coinside :( " + "\n"
                + " Intentalo otra vez");
                Interface interfaz = new Interface();
                this.setVisible(false);
                interfaz.setVisible(true);
            }
        }
        else{
            JOptionPane.showMessageDialog( null, "El usuario que autoriza no existe o la contraseña es incorrecta D:"+"\n"+"Porfi vuelve a intentarlo :)" );
            Interface interfaz = new Interface();
            this.setVisible(false);
            interfaz.setVisible(true);
        }
    }//GEN-LAST:event_jButton3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBack;
    private javax.swing.JLabel jLabelLoginWallpaper;
    private javax.swing.JLabel jLabelNewUser;
    private javax.swing.JLabel jLabelNewUserWallpaper;
    private javax.swing.JLabel jLabelUserIcon;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JPasswordField jPasswordNewUser1;
    private javax.swing.JPasswordField jPasswordNewUser2;
    private javax.swing.JPasswordField jPasswordUserNewUser;
    private javax.swing.JTextField jTextFieldNewUserCharge;
    private javax.swing.JTextField jTextFieldNewUserName;
    private javax.swing.JTextField jTextFieldUser;
    private javax.swing.JTextField jTextFieldUserNewUser;
    // End of variables declaration//GEN-END:variables
}
